#!/usr/bin/sh
#
# Setup a development environment for waftools.
#


ALL=
YES=

while getopts ":ay" opt; do
	case $opt in
		a)
			echo "--> installing additional programs" >&2
			ALL=1
			;;
		y)
			echo "--> autoinstall  programs" >&2
			YES=-y
			;;
		\?)
			echo "invalid option command line option '-$OPTARG'." >&2
			echo "  option  description"
			echo "  -a      install additional programs (e.g. cppcheck)."
			echo "  -y      autoinstall additional programs."
			exit 1
			;;
	esac
done


echo "--> installing required development packages..."
sudo yum -y install \
				python-pip python-virtualenv python-wheel \
				python-chardet python-pygments python-jinja2 \
				wget indent meld sphinx python-sphinx \
				eclipse-pydev eclipse-pydev-mylyn

sudo yum -y groupinstall "C Development Tools and Libraries"


echo "--> installing pypi tools..."
pip install twine --user 


echo "--> installing build environment tools..."
sudo yum install -y cppcheck doxygen cmake

if [ $ALL ]
then
	for i in eclipse-cdt codeblocks;
	do
		sudo $YES yum install $i
	done
fi




