#!/usr/bin/sh
set -e

ALL=
YES=

while getopts ":ay" opt; do
	case $opt in
		a)
			echo "--> installing additional programs" >&2
			ALL=1
			;;
		y)
			echo "--> autoinstall  programs" >&2
			YES=-y
			;;
		\?)
			echo "invalid option command line option '-$OPTARG'." >&2
			echo "  option  description"
			echo "  -a      install additional programs (e.g. cppcheck)."
			echo "  -y      autoinstall additional programs."
			exit 1
			;;
	esac
done


echo "--> installing required development packages..."
sudo yum -y install \
				python-pip python-virtualenv python-wheel \
				python-chardet python-pygments python-jinja2 \
				wget indent meld sphinx python-sphinx \
				eclipse-pydev eclipse-pydev-mylyn

sudo yum -y groupinstall "C Development Tools and Libraries"


echo "--> installing pypi tools..."
pip install twine --user 
pip install sphinx-rtd-theme --user


echo "--> installing build environment tools..."
sudo yum install -y cppcheck doxygen cmake

if [ $ALL ]
then
	for i in eclipse-cdt codeblocks;
	do
		sudo $YES yum install $i
	done
fi

echo "--> install openwrt mips cross-compiler..."
url="http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/mikrotik"
release="OpenWrt-Toolchain-ar71xx-for-mips_34kc-gcc-4.8-linaro_uClibc-0.9.33.2"
package=$release.tar.bz2
tmp=`mktemp -d`
dst=$HOME/.local/share/openwrt
cd $tmp
wget $url/$package
tar jxvf $package
mkdir $HOME/.local/share/openwrt
mv $release/* $dst
cd $HOME
rm -rf $tmp
echo 'export PATH=$PATH:~/.local/share/openwrt/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin' >> $HOME/.bashrc





