#!/usr/bin/env python
# -*- encoding: utf-8 -*-

def build(bld):
	bld.shlib(
		target='saox',
		source=bld.path.ant_glob('src/*.c'),
		includes=['./include'],
		export_includes=['./include'],
		use=['saoy'],
	)

