#!/usr/bin/env python
# -*- encoding: utf-8 -*-

def build(bld):
	bld.stlib(
		target='saoz',
		source=bld.path.ant_glob('src/*.c'),
		includes=['./include'],
		export_includes=['./include'],
		cmake_skipme=True,
		eclipse_skipme=True,
	)

