#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Michel Mooij, michel.mooij7@gmail.com


import os
import waftools
from waftools import ccross


top = '.'
out = 'build'
prefix = 'output'


VERSION = waftools.version
APPNAME = 'waftools-test'


def options(opt):
	opt.add_option('--prefix', dest='prefix', default=prefix, help='installation prefix [default: %r]' % prefix)
	opt.load('ccross', tooldir=waftools.location)
	opt.load('msdev', tooldir=waftools.location)


def configure(conf):
	conf.load('ccross')
	conf.load('msdev')


def build(bld):
	ccross.build(bld, trees=['components'])


def dist(ctx):
	ctx.excl = '**/*~ .lock-w* .git/** %s/** %s/**' % (out, prefix)


# create commands for cross-compile environments
for var in ccross.variants():
	for ctx in ccross.contexts():
		name = ctx.__name__.replace('Context','').lower()
		class _t(ctx):
			__doc__ = "%ss '%s'" % (name, var)
			cmd = name + '_' + var
			variant = var


